apiVersion: v1
kind: Service
metadata:
  name: qryptell-websocket-service
spec:
  selector:
    app: qryptell-websocket
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 9000
      protocol: TCP
