apiVersion: apps/v1
kind: Deployment
metadata:
  name: qryptell-websocket-service
  labels:
    app: qryptell-websocket-service

spec:
  replicas: 1
  selector: 
    matchLabels:
      app: qryptell-websocket
  template:
    metadata:
      labels:
        app: qryptell-websocket
    spec:
      containers:
        - name: qryptell-websocket
          image: vaishakhgk/qryptell-websocket
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: qryptell-websocket-configmap
