apiVersion: apps/v1
kind: Deployment
metadata:
  name: qryptell-user-service
  labels:
    app: qryptell-user-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: qryptell-user
  template:
    metadata:
      labels:
        app: qryptell-user
    spec:
      containers:
        - name: qryptell-user
          image: vaishakhgk/qryptell-user
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: qryptell-user-configmap
