apiVersion: apps/v1
kind: Deployment
metadata:
  name: qryptell-auth-service
  labels:
    app: qryptell-auth-service

spec:
  replicas: 1
  selector: 
    matchLabels:
      app: qryptell-auth
  template:
    metadata:
      labels:
        app: qryptell-auth
    spec:
      containers:
        - name: qryptell-auth
          image: vaishakhgk/qryptell-auth
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: qryptell-auth-configmap
