apiVersion: apps/v1
kind: Deployment
metadata:
  name: qryptell-mail-service
  labels:
    app: qryptell-mail-service

spec:
  replicas: 1
  selector: 
    matchLabels:
      app: qryptell-mail
  template:
    metadata:
      labels:
        app: qryptell-mail
    spec:
      containers:
        - name: qryptell-mail
          image: vaishakhgk/qryptell-mail
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: qryptell-mail-configmap
