apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-mongodb-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/user-mongodb"
