apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-mysql-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/auth-mysql"
