apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: lunarloom.com
      http:
        paths:
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: lunarloom-websocket-service
                port:
                  number: 8001
